version: '3.8'
services:

  gstock:
    image: ezemarcel/gstock-gstock-api:1.0
    container_name: gstock_api
    depends_on:
      - postgresql
    ports:
      - 8281:80
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_GSTOCK=${DB_GSTOCK}
      - GSTOCK_PREFIX=${GSTOCK_PREFIX}
      - USER_PATH=users
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:80/health_check"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 10s

  users:
    image: ezemarcel/gstock-users-api:1.0
    container_name: users_api
    depends_on:
      - postgresql
    ports:
      - 8280:80
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - USER_PREFIX=${USER_PREFIX}
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:80/health_check"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 10s

  postgresql:
    image: postgres:14.1-alpine
    restart: always
    container_name: gstock_db
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgresql"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s

volumes:
  postgresql-volume:
