version: '3.8'
services:

  stock:
    image: ezemarcel/gstock-api:1.0
    container_name: stock_api
    depends_on:
      - postgresql
    ports:
      - 8281:80
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:80/status", "--header", "customer:admin"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    

  postgresql:
    image: postgres:14.1-alpine
    restart: always
    container_name: stock_db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgresql"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s

volumes:
  postgresql-volume:
